package com.exception;

public class TryWithMultipleTimesCatch {

	public static void main(String[] args) {
		int a=10,b=0;
		try {
			System.out.println(a/b);
		}
		catch(ArrayIndexOutOfBoundsException aoe)
		{
			aoe.printStackTrace();
		}
		catch(Exception e) {
			e.printStackTrace();
			}
		System.out.println("Hi");
		System.out.println("Hello");
	}

}
